#+TITLE: StumpWM Configuration
#+STARTUP: overview
#+OPTIONS: toc:4 h:4
#+PROPERTY: header-args :tangle init.lisp :noweb yes
#+TODO: | DISABLED
#+TODO: TODO | DONE

* Overview

  Single org file setup has worked well for my emacs configuration. I think
  configuring stumpwm the same way will also work well.

* License

  All the code I have in this file is free software. This also goes for the
  generated =init.el= file.

  #+begin_src common-lisp
    ;; Copyright 2017, Ahmet Vedat Hallac
    ;;
    ;; This program is free software: you can redistribute it and/or modify
    ;; it under the terms of the GNU General Public License as published by
    ;; the Free Software Foundation, either version 3 of the License, or
    ;; (at your option) any later version.
    ;;
    ;; This program is distributed in the hope that it will be useful,
    ;; but WITHOUT ANY WARRANTY; without even the implied warranty of
    ;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ;; GNU General Public License for more details.
    ;;
    ;; You should have received a copy of the GNU General Public License
    ;; along with this program.  If not, see <http://www.gnu.org/licenses/>.
  #+end_src


* How to Use this file

  This file contains configuration script snippets organized by different type
  of headings.

  Each snippet is an org mode source block. Each block can be edited in a
  separate buffer by pressing =C-c '= (or =M-x org-edit-special=). In order to
  add a new block, use =C-c C-, s= and add =common-lisp= as the block's
  language. Then You can edit the contents of the block as described above.

  For more information about source blocks, ou can consult the [[http://orgmode.org/manual/Working-with-source-code.html][relevant section]]
  in [[http://orgmode.org/manual/index.html][The Org Manual]].

  Using org-mode's tangle functionality fill generate ~init.lisp~ file.

** Disabling a code snippet

   When you want to disable a snippet, add ~:tangle no~ to the relevant source block.

   For example:

   #+begin_src common-lisp :tangle no
     ;;; This line will not be added to the generated configuration
   #+end_src

** Generating configuration file

   Execute =M-x org-babel-tangle=, or press =C-c C-v t= sequence to generate the
   startup files.

* Prelude

  First, pick up anything sbcl wants. I want my environments to be the same.

  This will load quicklisp, which is the most important part.

  #+begin_src common-lisp
    (load "~/.sbclrc")
  #+end_src

  For debugging swank (on port 4005) is used. Emacs has a corresponding setup.

  #+begin_src common-lisp
    (ql:quickload :swank)
    (defcommand swank () ()
                (swank:create-server
                 :dont-close t
                 :port swank::default-server-port))

  #+end_src

  The default prefix key, ~C-t~ is mostly OK, but it is used for creating tabs
  (pressing ~C-t t~ fixes this minor issue). I am still moving all window
  manager related keys to Super meta key.

  #+begin_src common-lisp
    (set-prefix-key (kbd "s-t"))
  #+end_src

  And finally, pull in all symbols of the ~:stumpwm~ package.

  #+begin_src common-lisp
    (in-package :stumpwm)
  #+end_src
** TODO Add emacs slime/swank setup here
* Default layout and groups

  Create two frames for emacs / shell pair in Default group. Also create some groups.

  #+begin_src common-lisp
    (split-frame-in-dir (current-group) :column 500/809)
    (add-group (current-screen) "Browse" :background t)
    (add-group (current-screen) "Code" :background t)
    (add-group (current-screen) "Chat" :background t)
    (add-group (current-screen) "Temp1" :background t)
    (add-group (current-screen) "Temp2" :background t)
    (add-group (current-screen) "Temp3" :background t)
    (add-group (current-screen) "Float-1" :background t :type 'float-group)
    (add-group (current-screen) "Float-2" :background t :type 'float-group)

  #+end_src
* Appearance

** TTF memory leak work around

   This is a work-around for [[https://github.com/stumpwm/stumpwm/issues/474#issuecomment-481885037][Issue#474]] (see the [[https://github.com/stumpwm/stumpwm/issues/474#issuecomment-481885037][relevant post]])

   #+begin_src common-lisp :tangle no
     (run-with-timer
      900 900
      (lambda ()
        (loop for font in (stumpwm::screen-fonts (current-screen))
           when (typep font 'xft:font)
           do (clrhash (xft::font-string-line-bboxes font))
             (clrhash (xft::font-string-line-alpha-maps font))
             (clrhash (xft::font-string-bboxes font))
             (clrhash (xft::font-string-alpha-maps font)))))
   #+end_src
** Pick up a fancy font

   #+begin_src common-lisp :tangle no
     (ql:quickload :clx-truetype)
     (load-module "ttf-fonts")
     (set-font (make-instance 'xft:font :family "DejaVu Sans Mono" :subfamily "Book" :size 16))
   #+end_src
* Mouse Focus Policy

  Just old school

  #+begin_src common-lisp
    (setf *mouse-focus-policy* :click)
  #+end_src

* OSD handler

  This is not really a standard thing. I use pqiv solely for displaying some on
  screen display messages. So I need to float the window, and make it lose focus.

  I could not handle this with a single hook. Currently, one hook handles the
  floating, and the other handles the focus. Also, when I try to go full screen,
  there is a flicker, which I could not get rid of. I may work on it if it
  becomes too much of a hassle.

  *NOTE*: This is not working at the moment. I disabled OSD until I can solve
   its problems.

  #+begin_src common-lisp
    (defun osd-new-window-hook (new-window)
      (when (window-matches-properties-p new-window :instance "pqiv")
        (push-event (lambda ()
                      (if (not (typep (current-group) 'float-group))
                          (float-window new-window (current-group)))
                      (push-event (lambda ()
                                    (push new-window (group-on-top-windows (current-group)))
                                    (setf (window-fullscreen new-window) t)))))))

    (defun osd-focus-window-hook (new-window old-window)
      (when (window-matches-properties-p new-window :instance "pqiv")
        (push-event (lambda ()
                      (focus-window old-window)))))

    (add-hook *new-window-hook* #'osd-new-window-hook)

    (add-hook *focus-window-hook* #'osd-focus-window-hook)
  #+end_src
* Key bindings

** Corrections to *root-map*
   #+begin_src common-lisp
     (define-key *root-map* (kbd "c") "exec /usr/bin/uxterm")
     (define-key *root-map* (kbd "C-c") "exec /usr/bin/uxterm")

   #+end_src

** Fake keys
   These are fake cursors for my tiny motospeed

   #+begin_src common-lisp
     ;; TODO: Convert to loop, add all modifier combinations:
     ;; S, C, M, and all their permutations
     (define-key *top-map* (kbd "s-h") "meta Left")
     (define-key *top-map* (kbd "s-j") "meta Down")
     (define-key *top-map* (kbd "s-k") "meta Up")
     (define-key *top-map* (kbd "s-l") "meta Right")

     (define-key *top-map* (kbd "s-C-h") "meta C-Left")
     (define-key *top-map* (kbd "s-C-j") "meta C-Down")
     (define-key *top-map* (kbd "s-C-k") "meta C-Up")
     (define-key *top-map* (kbd "s-C-l") "meta C-Right")

     (define-key *top-map* (kbd "s-H") "meta S-Left")
     (define-key *top-map* (kbd "s-J") "meta S-Down")
     (define-key *top-map* (kbd "s-K") "meta S-Up")
     (define-key *top-map* (kbd "s-L") "meta S-Right")

     (define-key *top-map* (kbd "s-C-H") "meta C-S-Left")
     (define-key *top-map* (kbd "s-C-J") "meta C-S-Down")
     (define-key *top-map* (kbd "s-C-K") "meta C-S-Up")
     (define-key *top-map* (kbd "s-C-L") "meta C-S-Right")
   #+end_src
** Group management keys

   These keys give faster access to groups - after they are created.

   #+begin_src common-lisp
     (define-key *top-map* (kbd "s-G") "gselect")

     (define-key *top-map* (kbd "s-1") "gselect 1")
     (define-key *top-map* (kbd "s-2") "gselect 2")
     (define-key *top-map* (kbd "s-3") "gselect 3")
     (define-key *top-map* (kbd "s-4") "gselect 4")
     (define-key *top-map* (kbd "s-5") "gselect 5")
     (define-key *top-map* (kbd "s-6") "gselect 6")
     (define-key *top-map* (kbd "s-7") "gselect 7")
     (define-key *top-map* (kbd "s-8") "gselect 8")
     (define-key *top-map* (kbd "s-9") "gselect 9")

     (define-key *top-map* (kbd "s-C-0") "gmove 10")
     (define-key *top-map* (kbd "s-C-1") "gmove 1")
     (define-key *top-map* (kbd "s-C-2") "gmove 2")
     (define-key *top-map* (kbd "s-C-3") "gmove 3")
     (define-key *top-map* (kbd "s-C-4") "gmove 4")
     (define-key *top-map* (kbd "s-C-5") "gmove 5")
     (define-key *top-map* (kbd "s-C-6") "gmove 6")
     (define-key *top-map* (kbd "s-C-7") "gmove 7")
     (define-key *top-map* (kbd "s-C-8") "gmove 8")
     (define-key *top-map* (kbd "s-C-9") "gmove 9")
     (define-key *top-map* (kbd "s-C-0") "gmove 10")
   #+end_src
** Convenience keys

   Just some keys to speed up comnmon operations.

   #+begin_src common-lisp
     (define-key *top-map* (kbd "s-D") "exec rofi -show-icons -show drun")
     (define-key *top-map* (kbd "s-d") "exec rofi -show-icons -show run")
     (define-key *top-map* (kbd "s-W") "exec rofi -show-icons -show window")
     (define-key *top-map* (kbd "s-w") "exec rofi -show-icons -show windowcd")
     (define-key *top-map* (kbd "s-F") "fullscreen")
     (define-key *top-map* (kbd "s-Q") "delete-window")
     (define-key *top-map* (kbd "s-C-Q") "kill-window")
   #+end_src
** Session Management

   These are the functions for system shutdown, reboot, session lock, user logout, etc.

   #+begin_src common-lisp
     (defvar *vh/session-map* (make-sparse-keymap)
       "Keymap for session and power management functions")

     (define-key *top-map* (kbd "s-p") *vh/session-map*)

     (define-key *vh/session-map* (kbd "s-l") "exec loginctl lock-session")
     (define-key *vh/session-map* (kbd "s-o") "exec loginctl poweroff")
     (define-key *vh/session-map* (kbd "s-r") "exec loginctl reboot")
     (define-key *vh/session-map* (kbd "s-s") "exec loginctl suspend")
   #+end_src
** User keymap

   This is the equivalent ocf ~C-c~prefix in emacs:

   #+begin_src common-lisp
     (defvar *vh/user-map* (make-sparse-keymap)
       "Keymap for odds and ends")

     (define-key *top-map* (kbd "s-c") *vh/user-map*)
   #+end_src

   First, let's add keepass autotype.

   #+begin_src common-lisp
     (define-key *vh/user-map* (kbd "s-P") "exec /usr/bin/keepass --auto-type")
   #+end_src

   And the two clipboard functions (selection to clipboard and vice versa.

   #+begin_src common-lisp
     (define-key *vh/user-map* (kbd "c") "exec xsel | xsel -i -b")
     (define-key *vh/user-map* (kbd "C") "exec xsel -b | xsel -i")
   #+end_src
** ACPI Function Keys
   These are the hardware control keys.

   #+begin_src common-lisp
     (define-key *top-map* (kbd "XF86MonBrightnessUp") "exec light -A 5")
     (define-key *top-map* (kbd "XF86MonBrightnessDown") "exec light -U 5")
     (define-key *top-map* (kbd "XF86AudioMute") "exec pactl set-sink-mute 1 toggle")
     (define-key *top-map* (kbd "XF86AudioMicMute") "exec pactl set-source-mute 2 toggle")
     (define-key *top-map* (kbd "XF86AudioRaiseVolume") "exec pactl set-sink-volume 1 +5%")
     (define-key *top-map* (kbd "XF86AudioLowerVolume") "exec pactl set-sink-volume 1 -5%")
   #+end_src
** Convenience functions
   #+begin_src common-lisp
     (define-key *top-map* (kbd "s-i") "time")
     (define-key *top-map* (kbd "s-:") "eval")
     (define-key *top-map* (kbd "s-;") "colon")
   #+end_src
** Frame splitting keys
   #+begin_src common-lisp
     (define-key *root-map* (kbd "s-s") "vsplit 2/3")
     (define-key *root-map* (kbd "s-S") "hsplit 2/3")
   #+end_src
* Fix GDK3 Mouse wheel
  I haven't really researched why, but according to [[https://github.com/stumpwm/stumpwm/wiki/FAQ][StumpWM FAQ]], the following
  environment variable is required to make the mouse wheel work in GTK3 applications.

  #+begin_src common-lisp
    (require 'sb-posix)

    (sb-posix:setenv "GDK_CORE_DEVICE_EVENTS" "1" 1)
  #+end_src
* Fix QT5 font scale factors

  #+begin_src common-lisp
    (sb-posix:setenv "QT_AUTO_SCREEN_SCALE_FACTOR" "0" 1)
  #+end_src

* Run all my scripts and helpers

  I use the ~lxsession~ program to maintain the scripts and services that I
  want. Without this, it is difficult to ensure they are all dead when I exit
  the window manager.

  ~lxsession~ also provides the xsettings daemon - which I need for configuring
  GTK3 look and feel.

  The configuration files for ~lxsession~ are at [[file:~/.config/lxsession/stumpwm][~/.config/lxsession/stumpwm]].

   #+begin_src common-lisp
    (run-prog "/usr/bin/lxsession" :args (split-string "-e stumpwm -s stumpwm" " ") :wait nil)
   #+end_src

* Some window customizations
** New window tweaks

   #+begin_src common-lisp
     (defun new-window-adjustments (new-window)
       (when (or (window-matches-properties-p new-window :instance "gitk")
                 (window-matches-properties-p new-window :instance "git-gui"))
         (setf (window-fullscreen new-window) t)))

     (add-hook *new-window-hook* #'new-window-adjustments)
   #+end_src

   I want my dialog windows to float.

   Not sure about transients. Use ~window-transient-p~ instead?

   #+begin_src common-lisp
     (defun float-dialogs-hook (win)
       (let ((grp (current-group)) )
         (when (and (not (typep grp 'float-group))
                    (or
                     (eq (window-type win) :dialog)
                     (string-match (window-res win) "pinentry-gtk-2")))
           (float-window win grp)
           (focus-window win t))))

     (add-hook *new-window-hook* #'float-dialogs-hook)
   #+end_src

* Log stumpwm

  Send all logs to [[file:~/.cache/stumpwm/log][~/.cache/stumpwm/log]].

  #+begin_src common-lisp
    (redirect-all-output "~/.cache/stumpwm/log")
  #+end_src
